<?xml version="1.0"?>
<robot name="simple_humanoid" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="M_PI" value="3.1415926535897931"/>
  <xacro:property name="torso_height" value="0.6"/>
  <xacro:property name="torso_width" value="0.3"/>
  <xacro:property name="torso_depth" value="0.2"/>
  <xacro:property name="head_radius" value="0.1"/>
  <xacro:property name="upper_arm_length" value="0.4"/>
  <xacro:property name="lower_arm_length" value="0.35"/>
  <xacro:property name="upper_leg_length" value="0.5"/>
  <xacro:property name="lower_leg_length" value="0.45"/>
  <xacro:property name="foot_length" value="0.15"/>
  <xacro:property name="foot_width" value="0.08"/>
  <xacro:property name="foot_height" value="0.05"/>

  <!-- Torso -->
  <link name="torso">
    <visual>
      <geometry>
        <box size="${torso_depth} ${torso_width} ${torso_height}"/>
      </geometry>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${torso_depth} ${torso_width} ${torso_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.5" ixy="0" ixz="0" iyy="0.5" iyz="0" izz="0.5"/>
    </inertial>
  </link>

  <!-- Head -->
  <link name="head">
    <visual>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="skin">
        <color rgba="0.8 0.6 0.4 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.02"/>
    </inertial>
  </link>

  <!-- Neck joint -->
  <joint name="neck_joint" type="revolute">
    <parent link="torso"/>
    <child link="head"/>
    <origin xyz="0 0 ${torso_height/2 + head_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="1"/>
  </joint>

  <!-- Left shoulder -->
  <link name="left_upper_arm">
    <visual>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="left_shoulder_joint" type="revolute">
    <parent link="torso"/>
    <child link="left_upper_arm"/>
    <origin xyz="${torso_depth/2} ${torso_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="50" velocity="1"/>
  </joint>

  <!-- Left elbow -->
  <link name="left_lower_arm">
    <visual>
      <geometry>
        <cylinder length="${lower_arm_length}" radius="0.04"/>
      </geometry>
      <origin xyz="0 0 ${-lower_arm_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${lower_arm_length}" radius="0.04"/>
      </geometry>
      <origin xyz="0 0 ${-lower_arm_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.6"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
  </link>

  <joint name="left_elbow_joint" type="revolute">
    <parent link="left_upper_arm"/>
    <child link="left_lower_arm"/>
    <origin xyz="0 0 ${-upper_arm_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="${M_PI/2}" effort="30" velocity="1"/>
  </joint>

  <!-- Right shoulder -->
  <link name="right_upper_arm">
    <visual>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="right_shoulder_joint" type="revolute">
    <parent link="torso"/>
    <child link="right_upper_arm"/>
    <origin xyz="${torso_depth/2} ${-torso_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="50" velocity="1"/>
  </joint>

  <!-- Right elbow -->
  <link name="right_lower_arm">
    <visual>
      <geometry>
        <cylinder length="${lower_arm_length}" radius="0.04"/>
      </geometry>
      <origin xyz="0 0 ${-lower_arm_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${lower_arm_length}" radius="0.04"/>
      </geometry>
      <origin xyz="0 0 ${-lower_arm_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="0.6"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
  </link>

  <joint name="right_elbow_joint" type="revolute">
    <parent link="right_upper_arm"/>
    <child link="right_lower_arm"/>
    <origin xyz="0 0 ${-upper_arm_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="${M_PI/2}" effort="30" velocity="1"/>
  </joint>

  <!-- Left hip -->
  <link name="left_upper_leg">
    <visual>
      <geometry>
        <cylinder length="${upper_leg_length}" radius="0.06"/>
      </geometry>
      <origin xyz="0 0 ${-upper_leg_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${upper_leg_length}" radius="0.06"/>
      </geometry>
      <origin xyz="0 0 ${-upper_leg_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="1.2"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.02"/>
    </inertial>
  </link>

  <joint name="left_hip_joint" type="revolute">
    <parent link="torso"/>
    <child link="left_upper_leg"/>
    <origin xyz="${-torso_depth/2} ${torso_width/2} ${-torso_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="1"/>
  </joint>

  <!-- Left knee -->
  <link name="left_lower_leg">
    <visual>
      <geometry>
        <cylinder length="${lower_leg_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-lower_leg_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${lower_leg_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-lower_leg_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.015" ixy="0" ixz="0" iyy="0.015" iyz="0" izz="0.015"/>
    </inertial>
  </link>

  <joint name="left_knee_joint" type="revolute">
    <parent link="left_upper_leg"/>
    <child link="left_lower_leg"/>
    <origin xyz="0 0 ${-upper_leg_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="${M_PI/2}" effort="80" velocity="1"/>
  </joint>

  <!-- Left foot -->
  <link name="left_foot">
    <visual>
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_height}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="left_ankle_joint" type="revolute">
    <parent link="left_lower_leg"/>
    <child link="left_foot"/>
    <origin xyz="0 0 ${-lower_leg_length}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-M_PI/6}" upper="${M_PI/6}" effort="20" velocity="1"/>
  </joint>

  <!-- Right hip -->
  <link name="right_upper_leg">
    <visual>
      <geometry>
        <cylinder length="${upper_leg_length}" radius="0.06"/>
      </geometry>
      <origin xyz="0 0 ${-upper_leg_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${upper_leg_length}" radius="0.06"/>
      </geometry>
      <origin xyz="0 0 ${-upper_leg_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="1.2"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.02"/>
    </inertial>
  </link>

  <joint name="right_hip_joint" type="revolute">
    <parent link="torso"/>
    <child link="right_upper_leg"/>
    <origin xyz="${-torso_depth/2} ${-torso_width/2} ${-torso_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="1"/>
  </joint>

  <!-- Right knee -->
  <link name="right_lower_leg">
    <visual>
      <geometry>
        <cylinder length="${lower_leg_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-lower_leg_length/2}" rpy="${M_PI/2} 0 0"/>
      <material name="light_gray">
        <color rgba="0.7 0.7 0.7 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${lower_leg_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-lower_leg_length/2}" rpy="${M_PI/2} 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.015" ixy="0" ixz="0" iyy="0.015" iyz="0" izz="0.015"/>
    </inertial>
  </link>

  <joint name="right_knee_joint" type="revolute">
    <parent link="right_upper_leg"/>
    <child link="right_lower_leg"/>
    <origin xyz="0 0 ${-upper_leg_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="${M_PI/2}" effort="80" velocity="1"/>
  </joint>

  <!-- Right foot -->
  <link name="right_foot">
    <visual>
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_height}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="right_ankle_joint" type="revolute">
    <parent link="right_lower_leg"/>
    <child link="right_foot"/>
    <origin xyz="0 0 ${-lower_leg_length}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-M_PI/6}" upper="${M_PI/6}" effort="20" velocity="1"/>
  </joint>

  <!-- Gazebo materials -->
  <gazebo reference="torso">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="head">
    <material>Gazebo/Pink</material>
  </gazebo>

  <gazebo reference="left_upper_arm">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="left_lower_arm">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="right_upper_arm">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="right_lower_arm">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="left_upper_leg">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="left_lower_leg">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="left_foot">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="right_upper_leg">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="right_lower_leg">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="right_foot">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- Gazebo plugin for joint state publisher -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <namespace>/simple_humanoid</namespace>
      </ros>
      <update_rate>30</update_rate>
      <joint_name>neck_joint</joint_name>
      <joint_name>left_shoulder_joint</joint_name>
      <joint_name>left_elbow_joint</joint_name>
      <joint_name>right_shoulder_joint</joint_name>
      <joint_name>right_elbow_joint</joint_name>
      <joint_name>left_hip_joint</joint_name>
      <joint_name>left_knee_joint</joint_name>
      <joint_name>left_ankle_joint</joint_name>
      <joint_name>right_hip_joint</joint_name>
      <joint_name>right_knee_joint</joint_name>
      <joint_name>right_ankle_joint</joint_name>
    </plugin>
  </gazebo>
</robot>