openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the RAG chatbot system for the Physical AI Humanoid Robotics book
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://api.rag-chatbot.example.com
    description: Production server

paths:
  /sessions:
    post:
      summary: Create a new chat session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: Optional user identifier
              example:
                user_id: "user-12345"
      responses:
        '201':
          description: Session created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    format: uuid
                    description: Unique identifier for the session
                  created_at:
                    type: string
                    format: date-time
                    description: Timestamp when session was created
              example:
                session_id: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                created_at: "2025-12-25T10:00:00Z"

  /sessions/{session_id}:
    get:
      summary: Get session details
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Session details
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    format: uuid
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  expires_at:
                    type: string
                    format: date-time

  /sessions/{session_id}/messages:
    get:
      summary: Get message history for a session
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Message history
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        role:
                          type: string
                          enum: [user, assistant]
                        content:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
    post:
      summary: Send a message to the chatbot
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content:
                  type: string
                  description: The message content
                selected_text_context:
                  type: string
                  description: Optional text selection context
              example:
                content: "What are the key principles of humanoid robotics?"
                selected_text_context: "The fundamental principles include kinematics, dynamics, and control theory."
      responses:
        '200':
          description: Response from the chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                    format: uuid
                  response:
                    type: string
                    description: The chatbot's response
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        chunk_id:
                          type: string
                          format: uuid
                        chapter_name:
                          type: string
                        module_path:
                          type: string
                        relevance_score:
                          type: number
                          format: float
                        source_url:
                          type: string
                          format: uri
                        source_text:
                          type: string
                      example:
                        chunk_id: "b2c3d4e5-f6g7-8901-2345-67890abcdef1"
                        chapter_name: "Introduction to Robotics"
                        module_path: "module-01-ros2/"
                        relevance_score: 0.85
                        source_url: "/docs/intro-to-robotics"
                        source_text: "Robotics is an interdisciplinary field..."
                example:
                  message_id: "c3d4e5f6-g7h8-9012-3456-7890abcdef12"
                  response: "The key principles of humanoid robotics include kinematics for motion planning, dynamics for understanding forces and movement, and control theory for managing the robot's behavior..."
                  citations:
                    - chunk_id: "b2c3d4e5-f6g7-8901-2345-67890abcdef1"
                      chapter_name: "Introduction to Robotics"
                      module_path: "module-01-ros2/"
                      relevance_score: 0.85
                      source_url: "/docs/intro-to-robotics"
                      source_text: "Robotics is an interdisciplinary field..."